# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Sobre NIPPE
    url: about
    weight: 10
  - name: Equipo
    url: equipo
    weight: 20
  - name: Novedades
    url: post
    weight: 30
  - name: Investigaciones
    url: investigacion
    weight: 40
  - name: Publicaciones
    url: publicacion
    weight: 50
  - name: Formación
    identifier: formacion
    url: formacion
    weight: 60
  - name: Posgrado
    parent: formacion
    url: formacion/posgrado
    weight: 60
  - name: Pregrado
    parent: formacion
    url: formacion/pregrado
    weight: 60
  - name: Difusión científica
    url: difusion
    weight: 70
  - name: Extensión
    url: extension
    weight: 80
  - name: Contacto
    url: contacto
    weight: 90
